GET https://juicy-backend-benitopedro13.vercel.app/categories
###
GET https://juicy-backend-benitopedro13.vercel.app/categories/1
###
POST https://juicy-backend-benitopedro13.vercel.app/categories
Content-Type: application/json

{
    "name": "Categpry 1"
}
###
PATCH https://juicy-backend-benitopedro13.vercel.app/categories/1
Content-Type: application/json

{
    "name": "Category Update"
}
###
DELETE https://juicy-backend-benitopedro13.vercel.app/categories/4