GET https://juicy-backend-benitopedro13.vercel.app/products
###
GET https://juicy-backend-benitopedro13.vercel.app/products/1
###
POST https://juicy-backend-benitopedro13.vercel.app/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 333,
    "categoryId": 5
}
###
PATCH https://juicy-backend-benitopedro13.vercel.app/products/1
Content-Type: application/json

{
    "name": "Product Update"
}
###
DELETE https://juicy-backend-benitopedro13.vercel.app/products/2