version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: sh -c 'chmod +x wait-for-it.sh && ./wait-for-it.sh -t 120 db:3306 -- npm run start:prod'

  db:
    image: mysql:8.0.30-debian
    env_file:
      - .env